"""Dump every number the results chapter cites from the saved pipeline outputs.

This script is the single source of truth for the Experimental Results and
Analysis chapter: it reads only deterministic file artifacts written by the
pipeline (``outputs/<strain>/`` and ``reports/``) and writes a markdown
summary to ``reports/verified_stats.md``.

Run from ``multiomics_graph/``:  python scripts/verify_counts.py
"""

import ast
import re
import sys
from pathlib import Path

import pandas as pd

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "outputs"
REPORTS = BASE / "reports"

STRAINS = ["B36", "MS_14384", "MS_14385", "MS_14386", "MS_14387"]
REL_ORDER = [
    ("gene", "genomic_proximity", "gene"),
    ("gene", "transcriptional_correlation", "gene"),
    ("gene", "encodes", "protein"),
    ("protein", "abundance_correlation", "protein"),
    ("protein", "ppi", "protein"),
    ("gene", "in_pathway", "annotation"),
    ("gene", "cog_category", "annotation"),
    ("protein", "annotated_by", "annotation"),
    ("gene", "associated_with", "annotation"),
    ("protein", "member_of_cluster", "annotation"),
    ("metabolite", "in_pathway", "annotation"),
    ("metabolite", "metabolised_by", "protein"),
    ("metabolite", "abundance_correlation", "metabolite"),
]
HYPEREDGE_ORDER = [
    "multi_omics_triple",
    "kegg_pathway",
    "cog_category",
    "go_term",
    "ppi_cluster",
    "amr_mechanism",
    "metabolic_pathway",
]


def edge_counts(strain: str) -> dict:
    gd = OUT / strain / "graph"
    counts = {}
    if not gd.exists():
        return counts
    for csv in sorted(gd.glob("edges_*.csv")):
        parts = csv.stem.replace("edges_", "", 1).split("_")
        rel = "_".join(parts[1:-1])
        src, dst = parts[0], parts[-1]
        n = sum(1 for _ in open(csv, encoding="utf-8", errors="replace")) - 1
        counts[(src, rel, dst)] = n
    return counts


def parse_metadata(strain: str) -> dict:
    """Parse node counts from graph/heterodata_metadata.txt."""
    md = OUT / strain / "graph" / "heterodata_metadata.txt"
    nodes = {}
    if not md.exists():
        return nodes
    for line in md.read_text(encoding="utf-8", errors="replace").splitlines():
        m = re.match(r"\s+(\w+):\s+(\d+) nodes", line)
        if m:
            nodes[m.group(1)] = int(m.group(2))
    return nodes


def hyperedge_counts(strain: str) -> dict:
    f = OUT / strain / "graph" / "hyperedge_type_counts.csv"
    out = {}
    if f.exists():
        df = pd.read_csv(f)
        for _, r in df.iterrows():
            out[str(r.iloc[0])] = int(r.iloc[1])
    return out


def aligned_rows(strain: str) -> int:
    f = OUT / strain / "aligned_multiomics.csv"
    if not f.exists():
        return 0
    return sum(1 for _ in open(f, encoding="utf-8", errors="replace")) - 1


def genome_cds(strain: str) -> int:
    f = OUT / strain / "genome_genes.csv"
    if not f.exists():
        return 0
    return sum(1 for _ in open(f, encoding="utf-8", errors="replace")) - 1


def load_amr_report(strain: str) -> pd.DataFrame:
    f = REPORTS / f"{strain}_amr_report.csv"
    if f.exists():
        return pd.read_csv(f)
    return pd.DataFrame()


def layer_coverage(strain: str) -> list:
    f = REPORTS / f"amr_path_trace_{strain}.csv"
    if not f.exists():
        return []
    df = pd.read_csv(f, low_memory=False)
    if "layer_coverage" not in df.columns:
        return []
    return [int(x) for x in df["layer_coverage"].dropna().tolist()]


def concordance(strain: str) -> dict:
    f = REPORTS / f"amr_path_trace_{strain}.csv"
    out = {"concordant": 0, "discordant": 0, "neutral": 0, "unavailable": 0}
    if not f.exists():
        return out
    df = pd.read_csv(f, low_memory=False)
    if "rna_protein_concordance" not in df.columns:
        return out
    for v in df["rna_protein_concordance"].dropna():
        v = str(v).strip().lower()
        key = "unavailable" if v in ("", "nan", "unavailable", "none") else v
        out.setdefault(key, 0)
        out[key] += 1
    return out


def main() -> None:
    lines = []
    lines.append("# Verified Pipeline Statistics")
    lines.append("")
    lines.append(
        "> Generated by `scripts/verify_counts.py` from the saved deterministic "
        "outputs after the pipeline re-run + AMR enrichment. Every number in the "
        "results chapter is taken from this file."
    )
    lines.append("")

    # Per-strain table rows
    rows = []
    for s in STRAINS:
        ec = edge_counts(s)
        he = hyperedge_counts(s)
        nodes = parse_metadata(s)
        n_amr = 0
        rep = load_amr_report(s)
        if not rep.empty and "marker" in rep.columns:
            n_amr = len(rep)
        cov = layer_coverage(s)
        mean_cov = round(sum(cov) / len(cov), 2) if cov else 0.0
        rows.append(
            {
                "strain": s,
                "gene_nodes": nodes.get("gene", "-"),
                "protein_nodes": nodes.get("protein", "-"),
                "metabolite_nodes": nodes.get("metabolite", "-"),
                "annotation_nodes": nodes.get("annotation", "-"),
                "aligned_genes": aligned_rows(s),
                "genome_cds": genome_cds(s),
                "n_edges": sum(ec.values()),
                "n_hyperedges": sum(he.values()),
                "amr_markers": n_amr,
                "mean_layer_cov": mean_cov,
            }
        )

    lines.append("## A. Per-strain summary")
    lines.append("")
    lines.append("| Strain | gene nodes | protein nodes | metabolite | annotation | aligned genes | genome CDS | edges | hyperedges | AMR markers | mean layer coverage |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        lines.append(
            f"| {r['strain']} | {r['gene_nodes']} | {r['protein_nodes']} | "
            f"{r['metabolite_nodes']} | {r['annotation_nodes']} | "
            f"{r['aligned_genes']} | {r['genome_cds']} | {r['n_edges']} | "
            f"{r['n_hyperedges']} | {r['amr_markers']} | {r['mean_layer_cov']}/8 |"
        )
    lines.append("")

    # Edge counts per relation type
    lines.append("## B. Edge counts per relation type (enriched graphs)")
    lines.append("")
    lines.append("| Relation | " + " | ".join(STRAINS) + " |")
    lines.append("|" + "---|" * (len(STRAINS) + 1))
    for rel in REL_ORDER:
        cells = []
        for s in STRAINS:
            ec = edge_counts(s)
            cells.append(str(ec.get(rel, 0)))
        lines.append("| " + " --".join(rel) + " | " + " | ".join(cells) + " |")
    lines.append("")

    # Hyperedge counts per family
    lines.append("## C. Hyperedge counts per family")
    lines.append("")
    lines.append("| Family | " + " | ".join(STRAINS) + " |")
    lines.append("|" + "---|" * (len(STRAINS) + 1))
    for fam in HYPEREDGE_ORDER:
        cells = []
        for s in STRAINS:
            he = hyperedge_counts(s)
            cells.append(str(he.get(fam, 0)))
        lines.append(f"| {fam} | " + " | ".join(cells) + " |")
    lines.append("")

    # AMR per-strain report
    lines.append("## D. AMR manifest resolution (per-strain report)")
    lines.append("")
    for s in STRAINS:
        rep = load_amr_report(s)
        lines.append(f"### {s}")
        lines.append("")
        if rep.empty:
            lines.append("No AMR determinants.")
            lines.append("")
            continue
        lines.append(
            "| marker | class | locus_tag | COG | KEGG paths | PPI nb | in_genome | in_aligned_omics |"
        )
        lines.append("|---|---|---|---|---|---|---|---|")
        for _, r in rep.iterrows():
            lines.append(
                f"| {r['marker']} | {r['amr_class']} | {r['locus_tag']} | "
                f"{r['COG']} | {r['n_kegg_pathways']} | {r['n_ppi_neighbors']} | "
                f"{r['in_genome']} | {r['in_aligned_omics']} |"
            )
        lines.append("")

    # Concordance
    lines.append("## E. RNA/protein concordance for AMR determinants")
    lines.append("")
    lines.append("| Strain | " + " | ".join(["concordant", "discordant", "neutral", "unavailable"]) + " |")
    lines.append("|" + "---|" * 5)
    for s in STRAINS:
        c = concordance(s)
        lines.append(
            f"| {s} | {c['concordant']} | {c['discordant']} | {c['neutral']} | {c['unavailable']} |"
        )
    lines.append("")

    # Cross-strain matrix
    f = REPORTS / "amr_cross_strain_matrix.csv"
    if f.exists():
        lines.append("## F. Cross-strain AMR presence matrix")
        lines.append("")
        df = pd.read_csv(f, index_col=0)
        lines.append("| Marker | " + " | ".join(df.columns) + " |")
        lines.append("|" + "---|" * (len(df.columns) + 1))
        for marker, row in df.iterrows():
            lines.append(
                f"| {marker} | " + " | ".join(str(int(v)) for v in row) + " |"
            )
        lines.append("")

    # Top candidates
    f = REPORTS / "amr_path_candidates.csv"
    if f.exists():
        lines.append("## G. Top candidate AMR-associated elements")
        lines.append("")
        df = pd.read_csv(f)
        top = df.head(25)
        has_stats = 'p_value' in df.columns
        if has_stats:
            lines.append(
                "| rank | candidate | name | type | #AMR det | #strains | min path | hub | p-value | q-value (FDR) | significant | evidence |"
            )
            lines.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
        else:
            lines.append(
                "| rank | candidate | name | type | #AMR det | #strains | min path | hub | evidence |"
            )
            lines.append("|---|---|---|---|---|---|---|---|---|")
        for _, r in top.iterrows():
            cells = [
                f"{r['rank']}", f"{r['candidate']}", f"{r['candidate_name']}",
                f"{r['entity_type']}", f"{r['number_of_amr_determinants']}",
                f"{r['number_of_strains']}", f"{r['minimum_path_length']}",
                f"{r.get('hub_candidate', '')}",
            ]
            if has_stats:
                pv = f"{r.get('p_value'):.3g}" if pd.notna(r.get('p_value')) else ""
                qv = f"{r.get('q_value'):.3g}" if pd.notna(r.get('q_value')) else ""
                sig = "yes" if r.get('enrichment_significant') else ""
                cells += [pv, qv, sig]
            cells.append(f"{r['evidence_types']}")
            lines.append("| " + " | ".join(str(c) for c in cells) + " |")
        lines.append("")

    out_file = REPORTS / "verified_stats.md"
    out_file.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_file}")
    print(f"  strains: {STRAINS}")
    for s in STRAINS:
        print(
            f"  {s}: aligned={aligned_rows(s)} cds={genome_cds(s)} "
            f"edges={sum(edge_counts(s).values())} "
            f"hyperedges={sum(hyperedge_counts(s).values())}"
        )


if __name__ == "__main__":
    main()